package database;

import client.Action;
import client.User;

/**
 * Database is a skeleton class that will be used later on to work with other classes.
 */
public class Database {

    /**
     * This method queries the database based on the object it received.
     * @param action An object of the class Action
     * @return if the query succeeded.
     */
    public boolean addAction(Action action){
        return true;
    }

    /**
     * This method queries the database to look if the user exists.
     * @param token A string that contains a token.
     * @return if the query succeeded.
     */
    public boolean loginCheck(String token){
        return true;
    }

    /**
     * This method stores the token in the database.
     * @param token An object that is generated by the server
     */
    public void storeToken(Token token){

    }

    /**
     * This method checks if the user exists in the database
     * @param username A string with the username
     * @return if the users exists or not
     */
    public boolean checkRegister(String username){
        return true;
    }

    /**
     * This method checks if the username and password combination exists in the database
     * @param user An user object with the password and username
     * @return if the username and password match
     */
    public boolean checkLogin(User user){
        return true;
    }

    /**
     * This method queries the database for a taken in the username and password match.
     * @return the token for the user
     */
    public Token returnToken(){
        Token token = new Token();
        return token;
    }

}
