package database;

import client.Action;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 * Database is a skeleton class that will be used later on to work with other classes.
 */
public class Database {

    /**
     * This method saves the object in the database.
     * @param action An object of the class Action
     * @return if the query succeeded.
     */
    public boolean addAction(Action action){
        return true;
    }

    /**
     * This method queries the database to look if the user exists.
     * @param token A string that contains a token.
     * @return if the query succeeded.
     */
    public boolean loginCheck(String token){

        try {
            Connection con = DriverManager.getConnection();
            PreparedStatement state = con.prepareStatement("select * from user_data WHERE user_data.token = token ");
            ResultSet Rs = state.executeQuery();

            if(Rs.getFetchSize() == 0){
                return false;
            }else {
                while (Rs.next()) {

                    System.out.println(Rs.getString(1));
                }
                con.close();
                return true;
            }


        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            return false;
        }

    }

    /**
     * This method stores the token in the database.
     * @param token An object that is generated by the server
     */
    public void storeToken(String token){
        try {
            Connection con = DriverManager.getConnection();
            PreparedStatement state = con.prepareStatement("INSERT INTO user_data (token, username, hashpassword, mail)\n" +
                    "VALUES ('1', '', '', '');");
            ResultSet rs = state.executeQuery();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());

        }
    }

    /**
     * This method checks if the user exists in the database
     * @param username A string with the username
     * @return if the users exists or not
     */
    public boolean checkRegister(String username){
        return true;
    }

    /**
     * This method checks if the username and password combination exists in the database
     * @param username A String with the username
     * @param password A String with the password
     * @return if the username and password match
     */
    public boolean checkLogin(String username, String password){
        return true;
    }

    /**
     * This method queries the database for a taken in the username and password match.
     * @param username A string with the username
     * @return the token for the user
     */
    public String returnToken(String username){ return ""; }

}
